/**
 * index/gist-sync.ts
 *
 * Reads index/manifest.json and creates or updates a GitHub Gist.
 * The Gist acts as a public JSON API endpoint for the ellocharlie org state.
 *
 * - First run: creates a new Gist and saves its ID to index/.gist-id
 * - Subsequent runs: updates the existing Gist
 *
 * Usage: GITHUB_TOKEN=ghp_... bun run index:sync
 *
 * Required env vars:
 *   GITHUB_TOKEN — personal access token or fine-grained PAT with "gist" scope
 */

import { resolve, join } from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface GistFile {
  content: string;
  filename?: string;
}

interface GistCreatePayload {
  description: string;
  public: boolean;
  files: Record<string, GistFile>;
}

interface GistUpdatePayload {
  description: string;
  files: Record<string, GistFile>;
}

interface GistResponse {
  id: string;
  html_url: string;
  description: string;
  updated_at: string;
  files: Record<string, { filename: string; size: number; raw_url: string }>;
}

interface GitHubErrorResponse {
  message: string;
  documentation_url?: string;
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dir, "..");
const MANIFEST_PATH = join(ROOT, "index", "manifest.json");
const GIST_ID_PATH = join(ROOT, "index", ".gist-id");

const GIST_DESCRIPTION = "ellocharlie org state — auto-generated by ellocharlie-engine";
const GIST_FILENAME = "ellocharlie-manifest.json";
const GITHUB_API = "https://api.github.com";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function requireEnv(name: string): string {
  const value = Bun.env[name];
  if (!value) {
    throw new Error(
      `Missing required environment variable: ${name}\n` +
        `Set it before running: ${name}=your_token bun run index:sync`
    );
  }
  return value;
}

async function readFileSafe(path: string): Promise<string | null> {
  try {
    return await Bun.file(path).text();
  } catch {
    return null;
  }
}

function makeHeaders(token: string): Record<string, string> {
  return {
    "Authorization": `Bearer ${token}`,
    "Accept": "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "ellocharlie-engine/0.1.0",
  };
}

async function handleResponse<T>(response: Response, context: string): Promise<T> {
  if (!response.ok) {
    let message = `HTTP ${response.status} ${response.statusText}`;
    try {
      const body = await response.json() as GitHubErrorResponse;
      message += `: ${body.message}`;
      if (body.documentation_url) {
        message += ` (see ${body.documentation_url})`;
      }
    } catch {
      // Could not parse error body
    }
    throw new Error(`${context} failed — ${message}`);
  }
  return response.json() as Promise<T>;
}

// ---------------------------------------------------------------------------
// Gist operations
// ---------------------------------------------------------------------------

async function createGist(token: string, content: string): Promise<GistResponse> {
  console.log("  Creating new Gist...");

  const payload: GistCreatePayload = {
    description: GIST_DESCRIPTION,
    public: true,
    files: {
      [GIST_FILENAME]: { content },
    },
  };

  const response = await fetch(`${GITHUB_API}/gists`, {
    method: "POST",
    headers: makeHeaders(token),
    body: JSON.stringify(payload),
  });

  return handleResponse<GistResponse>(response, "Gist creation");
}

async function updateGist(
  token: string,
  gistId: string,
  content: string
): Promise<GistResponse> {
  console.log(`  Updating Gist ${gistId}...`);

  const payload: GistUpdatePayload = {
    description: GIST_DESCRIPTION,
    files: {
      [GIST_FILENAME]: { content },
    },
  };

  const response = await fetch(`${GITHUB_API}/gists/${gistId}`, {
    method: "PATCH",
    headers: makeHeaders(token),
    body: JSON.stringify(payload),
  });

  return handleResponse<GistResponse>(response, "Gist update");
}

async function verifyGistExists(token: string, gistId: string): Promise<boolean> {
  const response = await fetch(`${GITHUB_API}/gists/${gistId}`, {
    headers: makeHeaders(token),
  });
  return response.status === 200;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  // 1. Load token
  const token = requireEnv("GITHUB_TOKEN");

  // 2. Read manifest
  console.log("📖 Reading manifest...");
  const manifestRaw = await readFileSafe(MANIFEST_PATH);
  if (!manifestRaw) {
    throw new Error(
      `index/manifest.json not found.\n` +
        `Run "bun run index:build" first to generate it.`
    );
  }

  // Validate it's parseable JSON
  let manifest: unknown;
  try {
    manifest = JSON.parse(manifestRaw);
  } catch (e) {
    throw new Error(`index/manifest.json is not valid JSON: ${e}`);
  }

  // Re-serialize with consistent formatting
  const content = JSON.stringify(manifest, null, 2) + "\n";

  // 3. Load or create Gist ID
  const existingGistId = await readFileSafe(GIST_ID_PATH);
  const gistId = existingGistId?.trim() ?? null;

  let result: GistResponse;

  if (gistId) {
    // Verify the Gist still exists (could have been deleted)
    const exists = await verifyGistExists(token, gistId);
    if (exists) {
      result = await updateGist(token, gistId, content);
    } else {
      console.warn(`  ⚠️  Gist ${gistId} not found — creating a new one`);
      result = await createGist(token, content);
    }
  } else {
    result = await createGist(token, content);
  }

  // 4. Persist Gist ID
  if (result.id !== gistId) {
    await Bun.write(GIST_ID_PATH, result.id + "\n");
    console.log(`  💾 Gist ID saved to index/.gist-id`);
  }

  // 5. Report
  const fileInfo = result.files[GIST_FILENAME];
  console.log(`\n✅ Gist synced successfully`);
  console.log(`   Gist ID  : ${result.id}`);
  console.log(`   URL      : ${result.html_url}`);
  console.log(`   Raw URL  : ${fileInfo?.raw_url ?? "(unavailable)"}`);
  console.log(`   Updated  : ${result.updated_at}`);
  console.log(`   Size     : ${fileInfo?.size ?? content.length} bytes`);
}

await main();
